import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppStateProvider } from "./management/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppStateProvider>
        <body
          className={`${inter.className} bg-light-pattern-mobile md:bg-light-pattern-tablet lg:bg-light-pattern-desktop bg-cover bg-Light-Gray dark:bg-Dark-Navy dark:bg-dark-pattern-mobile md:dark:bg-dark-pattern-tablet lg:dark:bg-dark-pattern-desktop`}
        >
          {children}
        </body>
      </AppStateProvider>
    </html>
  );
}
